### ISSUE TITLE
Can I have a brief explanation on how you compare the average computation time between different program?

### ISSUE THREAD

**Issue by andyyankai** [lubkoll/funcy#3]
In your paper about FunG you compare the computation speed between multiple programs. I can see there is a huge difference between your program and another traditional autodiff library. Is it possible to release the method or program that how you preform the speed testing between this seven software? I implemented FunG into CppAD and find the ranking can be much differnt comparing your ranking in the paper.(For example Adolc is much faster but FADBAD is almost the slowest one) I am also trying to compare my autodiff program with funG using std::chrono::high_resolution_clock. I can share my library with you if you want to take a look.
Best,

**Comment by lubkoll** [comment]
Already done:) A nice thing about the [Archive of Numerical Software](https://journals.ub.uni-heidelberg.de/index.php/ans/) is, that they require to submit not only your code, but also all experiments, cited in the publication, for verification by the reviewers. The code I used at this time is [here](https://github.com/lubkoll/FunG_AD_Comparison). As it my tests are now more than three years old it is of course possible that some libraries improved their performance in the meanwhile. If you have libraries for which the performance, as reported in my paper, significantly differs from your measurements, then I definitely would like to hear about it (and also like to see your test setup).

Performance testing has a lot of things that can go wrong. A.o. the following certainly is important:

- shut down everything you don't essentially need and disconnect from the internet. Everything that consumes CPU and RAM has a potential do mess up the results. If anything runs on the same core as the test, then the results will certainly be useless
- make sure to average over a large amount of evaluations. As the evaluation time is already very slow, variations due to hardware, operating system, other processes... have quite an impact on single measurements. So make sure to average over large numbers of evaluations.
- make sure to vary function arguments. In particular for FunG/funcy, I have learned this lesson myself when doing first measurements. Averaging over 1 million evaluations, the measurement found my code to be more than 1 million times faster. That was exciting... for a few seconds. Then I realized that I just did see the manifestation of FunG/funcy being more compiler-friendly than other implementations. The compiler did optimize everything away, except one single function call, as it realized that I was calling the same function over and over again.

If you have your library on github I will take look at it.
Best
